import React, { useRef } from "react";
import Icon from "../Icon";
import Button from "../Button";
import ReportCharts from "./ReportCharts";
import ReportTable from "./ReportTable";
import type { IAdminReport } from "../../../services/adminService";
import "./ReportViewer.css";

interface ReportViewerProps {
  report: IAdminReport;
  onClose: () => void;
}

const ReportViewer: React.FC<ReportViewerProps> = ({ report, onClose }) => {
  const viewerRef = useRef<HTMLDivElement>(null);

  const handleDownloadPDF = () => {
    window.print();
    // This triggers the browser print dialog, which is styled by our CSS for print
  };

  const formattedDate = new Date(report.generatedAt).toLocaleString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });

  return (
    <div className="viewer-overlay">
      <div className="viewer-container">
        
        <div className="viewer-actions hide-on-print">
          <Button label="Close" variant="ghost" icon={<Icon name="close" size="sm" />} onClick={onClose} />
          <Button label="Download PDF" variant="primary" icon={<Icon name="dashboard" size="sm" />} onClick={handleDownloadPDF} />
        </div>

        <div className="document-page" ref={viewerRef}>
          {/* Header */}
          <div className="document-header">
            <div className="doc-logo-section">
              <div className="doc-logo">
                <Icon name="dashboard" size="xl" color="white" />
              </div>
              <h1 className="doc-brand">HostelHub Management</h1>
            </div>
            <div className="doc-meta">
              <h2>{report.title}</h2>
              <p><strong>Report ID:</strong> {report.id}</p>
              <p><strong>Generated On:</strong> {formattedDate}</p>
              <p><strong>Generated By:</strong> Admin System</p>
            </div>
          </div>

          <hr className="doc-divider" />

          {/* Key Insights / Summary */}
          <div className="document-section">
            <h3 className="section-title">Summary KPI</h3>
            <div className="kpi-grid">
              {Object.keys(report.data || {}).filter(k => typeof report.data[k] === 'number' || typeof report.data[k] === 'string').map(key => (
                <div key={key} className="kpi-card">
                  <div className="kpi-label">{key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase())}</div>
                  <div className="kpi-value">{String(report.data[key])}</div>
                </div>
              ))}
            </div>
          </div>

          {/* Charts */}
          <div className="document-section no-page-break">
            <h3 className="section-title">Visual Analysis</h3>
            <ReportCharts type={report.type} data={report.data} />
          </div>

          {/* Detailed Table */}
          <div className="document-section">
            <h3 className="section-title">Detailed Breakdown</h3>
            <ReportTable type={report.type} data={report.data} />
          </div>

          {/* Footer */}
          <div className="document-footer">
            <p>Generated securely by HostelHub Automated Report System.</p>
            <p>Confidential and for internal management use only.</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportViewer;
